import unittest
from test_zhiqiang import TestZhiQiang
from HTMLTestRunner import HTMLTestRunner

# class TestReport(unittest.TestCase):
#     def report(self):
#         suite = unittest.TestSuite()
#         suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestZKScore))
#         suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestZhiQiang))
#         with open('HTMLReport.html', 'wb') as f:
#             runner = HTMLTestRunner(stream=f,
#                                     title='接口自动化测试报告',
#                                     # description='generated by HTMLTestRunner.',
#                                     verbosity=2
#                                     )
#             runner.run(suite)

if __name__=='__main__':
    suite = unittest.TestSuite()
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(TestZhiQiang))
    with open('../HTMLReport.html', 'wb') as f:
        runner = HTMLTestRunner(stream=f,
                                title='接口自动化测试报告',
                                #description='generated by HTMLTestRunner.',
                                verbosity=2
                                )
        runner.run(suite)
